const fs = require('fs');
const path = require('path');

// ============================================================
// ✏️  黑名單設定區 — 填入「不要」顯示的文件 ID
// 文件 ID = docs/ 資料夾內的相對路徑（不含副檔名）
// 例如：docs/王小明老師.md  →  '王小明老師'
//       docs/teachers/陳大華老師.md  →  'teachers/陳大華老師'
// ============================================================

const TEACHER_BLACKLIST = [
  // '某某老師',  // 不想出現在嘉中老師側邊欄的文件
  '嘉義高中超可怕出題老師'
];

const CLUB_BLACKLIST = [
  // '某某社',   // 不想出現在嘉中社團側邊欄的文件
];

// ============================================================
// 以下請勿修改
// ============================================================

const docsDir = path.join(__dirname, 'docs');

/**
 * 遞迴掃描 docs/，找出檔名包含 keyword 且不在黑名單內的文件
 */
function findDocsByKeyword(keyword, blacklist, dir = docsDir, baseDir = docsDir) {
  const items = [];
  if (!fs.existsSync(dir)) return items;

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      items.push(...findDocsByKeyword(keyword, blacklist, fullPath, baseDir));
    } else if (entry.name.match(/\.(md|mdx|html)$/) && entry.name.includes(keyword)) {
      const rel = path.relative(baseDir, fullPath);
      const docId = rel.replace(/\\/g, '/').replace(/\.(mdx?|html)$/, '');
      if (!blacklist.includes(docId)) {
        items.push({ type: 'doc', id: docId });
      }
    }
  }
  return items;
}

/**
 * 找 docs/ 裡第一個 .md 當佔位（白名單為空時防止 navbar 報錯用）
 */
function findFirstDoc(dir = docsDir, baseDir = docsDir) {
  if (!fs.existsSync(dir)) return null;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const found = findFirstDoc(fullPath, baseDir);
      if (found) return found;
    } else if (entry.name.match(/\.(md|mdx)$/) && !entry.name.startsWith('_')) {
      const rel = path.relative(baseDir, fullPath);
      return rel.replace(/\\/g, '/').replace(/\.(mdx?)$/, '');
    }
  }
  return null;
}

function buildSidebar(label, keyword, blacklist) {
  const items = findDocsByKeyword(keyword, blacklist);

  if (items.length > 0) {
    return [{ type: 'category', label, collapsed: false, items }];
  }

  // 沒有符合的文件時，放佔位符避免 navbar 報錯
  const fallback = findFirstDoc();
  if (fallback) {
    return [{ type: 'doc', id: fallback, label: `（${label}目前無條目）` }];
  }

  return [{ type: 'autogenerated', dirName: '.' }];
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 1. 所有條目：顯示全部
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // 2. 嘉中老師：檔名含「老師」，排除黑名單
  teacherSidebar: buildSidebar('嘉中老師', '老師', TEACHER_BLACKLIST),

  // 3. 嘉中社團：檔名含「社」，排除黑名單
  clubSidebar: buildSidebar('嘉中社團', '社', CLUB_BLACKLIST),
};

export default sidebars;
