const fs = require('fs');
const path = require('path');

// ============================================================
// ✏️  白名單設定區 — 在這裡填入要顯示的文件 ID
// 文件 ID = docs/ 資料夾內的相對路徑（不含副檔名）
// 例如：docs/王小明老師.md → '王小明老師'
//       docs/teachers/陳大華老師.md → 'teachers/陳大華老師'
// ============================================================

const TEACHER_WHITELIST = [
  // '王小明老師',
  // 'teachers/陳大華老師',
];

const CLUB_WHITELIST = [
  // '嘉義高中社團',
  // '小社',
  // 'clubs/棋社',
];

// ============================================================
// 以下請勿修改
// ============================================================

function buildItems(whitelist) {
  const docsDir = path.join(__dirname, 'docs');
  const validItems = [];

  for (const id of whitelist) {
    // 嘗試找出對應的實際檔案（支援 .md / .mdx / .html）
    const extensions = ['.md', '.mdx', '.html'];
    const exists = extensions.some((ext) =>
      fs.existsSync(path.join(docsDir, id + ext))
    );

    if (exists) {
      validItems.push({ type: 'doc', id });
    } else {
      console.warn(`[sidebars] 白名單中找不到文件：${id}，已略過。`);
    }
  }

  return validItems;
}

const teacherItems = buildItems(TEACHER_WHITELIST);
const clubItems = buildItems(CLUB_WHITELIST);

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 1. 所有條目：顯示全部
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // 2. 嘉中老師
  teacherSidebar:
    teacherItems.length > 0
      ? [
          {
            type: 'category',
            label: '嘉中老師',
            collapsed: false,
            items: teacherItems,
          },
        ]
      : [
          {
            type: 'html',
            value: '<span style="padding:8px;color:#999">（白名單尚未設定任何老師條目）</span>',
          },
        ],

  // 3. 嘉中社團
  clubSidebar:
    clubItems.length > 0
      ? [
          {
            type: 'category',
            label: '嘉中社團',
            collapsed: false,
            items: clubItems,
          },
        ]
      : [
          {
            type: 'html',
            value: '<span style="padding:8px;color:#999">（白名單尚未設定任何社團條目）</span>',
          },
        ],
};

export default sidebars;
