const fs = require('fs');
const path = require('path');

/**
 * 遞迴掃描 docs 資料夾，找出檔名包含特定關鍵字的文件
 * 回傳格式為 Docusaurus sidebar item 的 doc id 陣列
 */
function findDocsByKeyword(keyword, docsDir = path.join(__dirname, 'docs'), baseDir = null) {
  if (!baseDir) baseDir = docsDir;
  const items = [];

  if (!fs.existsSync(docsDir)) return items;

  const entries = fs.readdirSync(docsDir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(docsDir, entry.name);
    if (entry.isDirectory()) {
      items.push(...findDocsByKeyword(keyword, fullPath, baseDir));
    } else if (
      entry.name.includes(keyword) &&
      (entry.name.endsWith('.md') || entry.name.endsWith('.mdx') || entry.name.endsWith('.html'))
    ) {
      // 計算相對於 docs 的路徑作為 doc id（去掉副檔名）
      const rel = path.relative(baseDir, fullPath);
      const docId = rel.replace(/\\/g, '/').replace(/\.(mdx?|html)$/, '');
      items.push({ type: 'doc', id: docId });
    }
  }

  return items;
}

const teacherItems = findDocsByKeyword('老師');
const clubItems = findDocsByKeyword('社團');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 1. 所有條目：顯示全部
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // 2. 嘉中老師：檔名包含「老師」的文件
  teacherSidebar:
    teacherItems.length > 0
      ? [
          {
            type: 'category',
            label: '嘉中老師',
            collapsed: false,
            items: teacherItems,
          },
        ]
      : [
          {
            type: 'html',
            value: '<span style="padding:8px;color:#999">（尚無老師相關條目）</span>',
          },
        ],

  // 3. 嘉中社團：檔名包含「社團」的文件
  clubSidebar:
    clubItems.length > 0
      ? [
          {
            type: 'category',
            label: '嘉中社團',
            collapsed: false,
            items: clubItems,
          },
        ]
      : [
          {
            type: 'html',
            value: '<span style="padding:8px;color:#999">（尚無社團相關條目）</span>',
          },
        ],
};

export default sidebars;
